#!/bin/sh
### BEGIN INIT INFO
# Provides:          searcher-pod
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Searcher SSH Pod
# Description:       Starts the Searcher SSH Pod using podman
### END INIT INFO

NAME=searcher-pod
DAEMON=/usr/bin/podman
USER=searcher
POD_CONFIG=/home/searcher/pod-config/searcher-ssh-pod.yaml
POD_NAME=searcher-ssh-pod

# Exit if podman is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
    start)
        echo "Starting $NAME..."
        su -s /bin/sh $USER -c "cd ~ && $DAEMON play kube $POD_CONFIG"
        ;;
    stop)
        echo "Stopping $NAME..."
        su -s /bin/sh $USER -c "cd ~ && $DAEMON pod stop $POD_NAME"
        su -s /bin/sh $USER -c "cd ~ && $DAEMON pod rm -f $POD_NAME"
        ;;
    restart)
        $0 stop
        sleep 2
        $0 start
        ;;
    status)
        if su -s /bin/sh $USER -c "cd ~ && $DAEMON pod exists $POD_NAME"; then
            echo "$NAME is running"
            exit 0
        else
            echo "$NAME is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
