#!/bin/sh
### BEGIN INIT INFO
# Provides:          searcher-container
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Searcher SSH Container
# Description:       Starts a simple SSH container using podman
### END INIT INFO

DAEMON=/usr/bin/podman
USER=searcher
NAME=searcher-container

# PORT FORWARDS
SEARCHER_SSH_PORT=10022
SYNC_PROXY_PORT=25590
EL_P2P_PORT=30303
SEARCHER_INPUT_CHANNEL=27017

start_searcher_container() {
    # Create directory for openssh server public key
    mkdir -p /etc/searcher/ssh_hostkey
    chown searcher:searcher /etc/searcher/ssh_hostkey
    
    # Ensure /persistent/searcher is owned by the searcher user
    mkdir -p /persistent/searcher
    chown -R searcher:searcher /persistent/searcher

    echo "Starting $NAME..."
    su -s /bin/sh $USER -c "cd ~ && $DAEMON run -d \
        --name $NAME \
        -p ${SEARCHER_SSH_PORT}:22 \
        -p ${SYNC_PROXY_PORT}:${SYNC_PROXY_PORT} \
        -p ${EL_P2P_PORT}:${EL_P2P_PORT} \
        -p ${SEARCHER_INPUT_CHANNEL}:${SEARCHER_INPUT_CHANNEL} \
        -v /etc/searcher_key:/container_auth_keys:ro \
        -v /persistent/searcher:/persistent:rw \
        -v /etc/searcher/ssh_hostkey:/etc/searcher/ssh_hostkey:rw \
        -v /searcher_logs:/var/log/searcher:rw \
        docker.io/library/ubuntu:24.04 \
        /bin/sh -c ' \
            DEBIAN_FRONTEND=noninteractive apt-get update && \
            DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server && \
            mkdir -p /run/sshd && \
            mkdir -p /root/.ssh && \
            cp /container_auth_keys /root/.ssh/authorized_keys && \
            chmod 700 /root/.ssh && \
            chmod 600 /root/.ssh/authorized_keys && \
            cp /etc/ssh/ssh_host_ed25519_key.pub /etc/searcher/ssh_hostkey/host_key.pub && \
            /usr/sbin/sshd -D -e'"
}

case "$1" in
    start)
        start_searcher_container
        ;;
    stop)
        echo "Stopping $NAME..."
        su -s /bin/sh $USER -c "cd ~ && $DAEMON stop $NAME"
        su -s /bin/sh $USER -c "cd ~ && $DAEMON rm -f $NAME"
        ;;
    status)
        if su -s /bin/sh $USER -c "cd ~ && $DAEMON container exists $NAME"; then
            echo "$NAME is running"
            su -s /bin/sh $USER -c "cd ~ && $DAEMON ps"
            exit 0
        else
            echo "$NAME is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

exit 0