#!/bin/sh
### BEGIN INIT INFO
# Provides:          searcher-container
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Searcher SSH Container
# Description:       Starts a simple SSH container using podman
### END INIT INFO

DAEMON=/usr/bin/podman
USER=searcher
NAME=searcher-container
SEARCHER_SSH_PORT=10022
FB_STATE_DIFF_PORT=8547
TITAN_STATE_DIFF_PORT=8548
FB_RPC_PORT=8645
TITAN_RPC_PORT=8646
EL_P2P_PORT=30303
ENGINE_API_PORT=8551
SEARCHER_INPUT_PORT_1=27017
SEARCHER_INPUT_PORT_2=27018
IPTABLES="/usr/sbin/iptables"

case "$1" in
    start)

        mkdir -p /etc/searcher/ssh_hostkey
        chown searcher:searcher /etc/searcher/ssh_hostkey   
        
        echo "Starting $NAME..."
        su -s /bin/sh $USER -c "cd ~ && $DAEMON run -d \
            --name $NAME \
            -p ${SEARCHER_SSH_PORT}:22 \
            -p ${FB_STATE_DIFF_PORT}:${FB_STATE_DIFF_PORT} \
            -p ${TITAN_STATE_DIFF_PORT}:${TITAN_STATE_DIFF_PORT} \
            -p ${FB_RPC_PORT}:${FB_RPC_PORT} \
            -p ${TITAN_RPC_PORT}:${TITAN_RPC_PORT} \
            -p ${EL_P2P_PORT}:${EL_P2P_PORT} \
            -p ${ENGINE_API_PORT}:${ENGINE_API_PORT} \
            -v /etc/searcher_key:/container_auth_keys:ro \
            -v /persistent:/persistent \
            -v /etc/searcher/ssh_hostkey:/etc/searcher/ssh_hostkey:rw \
            -v /searcher_logs:/var/log/searcher \
            -v /var/volatile/jwt.hex:/secrets/jwt.hex:rw \
            docker.io/library/ubuntu:24.04 \
            /bin/sh -c ' \
                DEBIAN_FRONTEND=noninteractive apt-get update && \
                DEBIAN_FRONTEND=noninteractive apt-get install -y openssh-server && \
                mkdir -p /run/sshd && \
                mkdir -p /root/.ssh && \
                cp /container_auth_keys /root/.ssh/authorized_keys && \
                chmod 700 /root/.ssh && \
                chmod 600 /root/.ssh/authorized_keys && \
                cp /etc/ssh/ssh_host_ed25519_key.pub /etc/searcher/ssh_hostkey/host_key.pub && \
                /usr/sbin/sshd -D -e'"

        ;;
    stop)
        echo "Stopping $NAME..."
        su -s /bin/sh $USER -c "cd ~ && $DAEMON stop $NAME"
        su -s /bin/sh $USER -c "cd ~ && $DAEMON rm -f $NAME"
        ;;
    status)
        if su -s /bin/sh $USER -c "cd ~ && $DAEMON container exists $NAME"; then
            echo "$NAME is running"
            su -s /bin/sh $USER -c "cd ~ && $DAEMON ps"
            exit 0
        else
            echo "$NAME is not running"
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

exit 0