# Pod configuration for SSH server container
apiVersion: v1
kind: Pod
metadata:
  name: fluentbit-pod
  labels:
    app: fluentbit
spec:
  containers:
    - name: fluentbit
      image: docker.io/fluent/fluent-bit:latest
      # use https://docs.fluentbit.io/manual/installation/docker to debug, e.g.
      # image: docker.io/fluent/fluent-bit:3.2.4-debug
      volumeMounts:
        - name: logs-volume
          mountPath: /var/log/searcher
        - name: fluentbit-config
          mountPath: /fluentbit.conf
          readOnly: true
        - name: delayed-logs-volume
          mountPath: /var/log/fluentbit
      command: ["/fluent-bit/bin/fluent-bit"]
      args:
        - "--config"
        - "/fluentbit.conf"
  volumes:
    - name: logs-volume
      hostPath:
        path: /searcher_logs
        type: Directory
    - name: fluentbit-config
      hostPath:
        path: /etc/fluentbit/fluentbitd-config/fluentbit.conf
        type: File
    - name: delayed-logs-volume
      hostPath:
        path: /delayed_logs
        type: Directory
  restartPolicy: Always
  # Using vfs storage driver
  runtimeConfig:
    storage:
      driver: vfs

